@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

title Диаграмма контекста - Передача ставок в кол-центр

Person(client, "Клиент", "Физическое лицо")
Person(front_office, "Сотрудник фронт-офиса", "Менеджер отделения")
Person(back_office_deposit, "Сотрудник бэк-офиса", "Менеджер депозитов")
Person(back_office_credit, "Сотрудник бэк-офиса", "Менеджер кредитов")
Person(call_center_operator, "Оператор кол-центра", "Внутренний кол-центр")
Person(partner_call_center_operator, "Оператор партнёрского кол-центра", "Внешний партнёр")
Person(partner_call_center_manager, "Менеджер партнёрского кол-центра", "Внешний партнёр")

System(banking_system, "Банковская система 'Стандарт'", "Обеспечивает подачу и обработку заявок на депозиты онлайн")

System_Ext(partner_call_system, "Система партнёрского кол-центра", "Внешняя система")

Rel(client, banking_system, "Узнаёт условия, создаёт заявки на сайте или интернет-банке")
Rel(front_office, banking_system, "Создает заявки при офлайн-посещении клиента")
Rel(back_office_deposit, banking_system, "Обрабатывает депозитные заявки")
Rel(back_office_credit, banking_system, "Анализирует кредитные риски")
Rel(call_center_operator, banking_system, "Принимает звонки, информирует клиента об условиях, формирует заявки")
Rel(partner_call_center_operator, partner_call_system, "Принимает звонки, информирует клиента об условиях, формирует заявки")
Rel(partner_call_system, banking_system, "Работа с заявками")
Rel(banking_system, partner_call_center_manager, "Отправка письма с файлом про актуальные ставки")
Rel(partner_call_center_manager, partner_call_center_operator, "Передаёт файл с актуальными ставками")

@enduml